### ISSUE TITLE
Cross-filtering

### ISSUE THREAD

**Issue by FaGuel** [jku-vds-lab/lineup_powerbi#2]
Problem Description:
@VAISHALI-DHANOA 
Maybe you can describe what the problem is and add some screenshots for documentation. :)

**Comment by VAISHALI-DHANOA** [comment]
![image](https://user-images.githubusercontent.com/2544506/119988297-3d6e4a00-bfc6-11eb-8e4d-432ce271a1bc.png)
Cross-filtering is working with LineUp. Please change the Interaction in the Edit pane directly
